# Abstract
# Create sequentially the given extensions on the application linked postgresql addon

# extensions-as-comma-separated-string input example: 'lint,prettier:check,test:unit'

name: zReusable Create Postgresql Extention Matrix Workflow On Scalingo

on:
  workflow_call:
    inputs:
      extensions-as-comma-separated-string:
        required: true
        type: string
      application-name:
        required: true
        type: string

    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  get-extensions:
    uses: ./.github/workflows/_matrix-from-string.reusable.yml
    with:
      input-string: ${{ inputs.extensions-as-comma-separated-string }}
      separator: ","
      field: "extension"

  create-extension:
    name: " "
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli
    needs:
      - get-extensions
    strategy:
      fail-fast: true
      # Max parallel 1 assure we will run jobs sequencially
      max-parallel: 1
      matrix:
        extension: ${{ fromJSON(needs.get-extensions.outputs.matrix) }}

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: ${{matrix.extension}}
        run: |
          echo "CREATE extension ${{matrix.extension}}; \q" | scalingo --app ${{ inputs.application-name }} pgsql-console
