# Abstract
# Create sequentially the given views on the application linked postgresql addon

# views-as-comma-separated-string input example: 'view_siret_with_department_region,view_contact_requests'

name: zReusable Create Postgresql Views Matrix Workflow On Scalingo

on:
  workflow_call:
    inputs:
      views-as-comma-separated-string:
        required: true
        type: string
      application-name:
        required: true
        type: string

    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  get-views:
    uses: ./.github/workflows/_matrix-from-string.reusable.yml
    with:
      input-string: ${{ inputs.views-as-comma-separated-string }}
      separator: ","
      field: "views"

  refresh-views:
    name: " "
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli
    needs:
      - get-views
    strategy:
      fail-fast: true
      # Max parallel 1 assure we will run jobs sequencially
      max-parallel: 1
      matrix:
        view: ${{ fromJSON(needs.get-views.outputs.matrix) }}

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: ${{matrix.view}}
        run: |
          echo "REFRESH MATERIALIZED VIEW ${{matrix.view}}; \q" | scalingo --app ${{ inputs.application-name }} pgsql-console
