name: zReusable Scalingo Postgresql Addon Setup

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

      addon-plan-postgresql:
        required: true
        type: string

      reset:
        required: false
        type: boolean
        default: false

    secrets:
      SCALINGO_API_TOKEN:
        required: true

    outputs:
      status:
        description: "'addon-created' or 'addon-existed-previously' if successful"
        value: ${{ jobs.postgresql-addon-check-or-create.outputs.status || jobs.postgresql-addon-reset.outputs.status }}

jobs:
  addon-postgresql:
    name: Add the postgresql addon if not present
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli

    outputs:
      status: ${{ steps.postgresql-addon-check-or-create.outputs.status }}

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: Create PostgreSQL addon with the given plan if not present,
        if: inputs.reset == false
        id: postgresql-addon-check-or-create
        run: >-
          if 
          (( $(scalingo -a ${{ inputs.application-name }} addons | grep -c 'PostgreSQL.*running' ) >= 1 ));
          then echo "Addon already exist"; echo "status=addon-existed-previously" >> $GITHUB_OUTPUT;
          else echo "Creating addon"; 
          scalingo --app ${{ inputs.application-name }} addons-add postgresql ${{ inputs.addon-plan-postgresql }}
          && echo "status='addon-created'" >> $GITHUB_OUTPUT;
          fi;

      - name: Destroy and recreate the PostgreSQL addon.
        if: inputs.reset == true
        id: postgresql-addon-reset
        shell: bash
        run: >-
          set +e

          if 
          (( $(scalingo -a ${{ inputs.application-name }} addons | grep -c 'PostgreSQL.*running' ) == 0 ));
          then echo "Creating addon"; 
          scalingo --app ${{ inputs.application-name }} addons-add postgresql ${{ inputs.addon-plan-postgresql }}
          && echo "status='addon-created'" >> $GITHUB_OUTPUT
          && exit 0;
          fi
           
          ADDON_ID_LINE=$(scalingo -a ${{ inputs.application-name }} addons | grep 'PostgreSQL' )

          regex='PostgreSQL \| (.*) \| ${{ inputs.addon-plan-postgresql }}'

          [[ $ADDON_ID_LINE =~ $regex ]]

          set -e

          echo ${BASH_REMATCH[1]} | scalingo --app ${{ inputs.application-name }} addons-remove ${BASH_REMATCH[1]}

          scalingo --app ${{ inputs.application-name }} addons-add postgresql ${{ inputs.addon-plan-postgresql }}

          echo "status='addon-created'" >> $GITHUB_OUTPUT
