name: "Dev - Build front, back and deploy"

on:
#  push:
#    branches:
#      - dev

jobs:
  validation:
    uses: ./.github/workflows/fullcheck.yml

  build-front-artefact:
    uses: ./.github/workflows/build-front-artefact.yml

  build-back-artefact:
    uses: ./.github/workflows/build-back-artefact.yml

  deploy-dev:
    name: Deploy dev
    needs: [validation, build-front-artefact, build-back-artefact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: dev
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  notify-discord:
    name: Notify deploy success
    needs: [deploy-dev]
    uses: ./.github/workflows/cd-discord-notification.yml
    with:
      environment: dev
      tag: vTodo
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  merge-to-staging:
    needs: [deploy-dev]
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Push dev to staging
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch
          git push origin origin/dev:staging
