name: "Production - Build front, back and deploy"

on:
  push:
    branches:
      - main

jobs:
  build-front-artefact:
    uses: ./.github/workflows/build-front-artefact.yml

  build-back-artefact:
    uses: ./.github/workflows/build-back-artefact.yml

  deploy-prod:
    needs: [build-front-artefact, build-back-artefact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      envType: "prod"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN_V2 }}
