# This is a Work In Progress
name: CD-Feature application on scalingo

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*

env:
  application-name: 'immersion-facile'
  reference-application-name: 'immersion-facile-staging'
  node-version: '16.15.0'
  addon-plan-postgresql: 'postgresql-sandbox'

jobs:
  dynamic-variables:
    outputs:
      node-version: ${{ steps.node-version.outputs.value }}
      application-name: ${{ steps.application-name.outputs.value }}
      reference-application-name: ${{ steps.reference-application-name.outputs.value }}
      addon-plan-postgresql: ${{ steps.addon-plan-postgresql.outputs.value }}
      deployment-owner-type: ${{ steps.deployment-owner-type.outputs.value }}
      is-discord-hooked: ${{ steps.is-discord-hooked.outputs.value }}
      deployed-domain: ${{ steps.deployed-domain.outputs.value }}
      deployed-app-name: ${{ steps.deployed-app-name.outputs.value }}

    runs-on: ubuntu-latest
    steps:
      - name: Node version from env variable
        id: node-version
        run: |
          NODE_VERSION=${{ env.node-version }}
          echo "::set-output name=value::$NODE_VERSION"

      - name: Deployed application base name
        id: application-name
        run: |
          APPLICATION_NAME=${{ env.application-name }}
          BRANCH_SHORT_REF=$(echo ${{ github.event.ref }} | cut -d'/' -f 4)
          APPLICATION_TRIMMED_NAME=$(echo $APPLICATION_NAME-$BRANCH_SHORT_REF | cut -c1-47)
          echo "::set-output name=value::$APPLICATION_TRIMMED_NAME"

      - name: Reference application (to copy config / db from)
        id: reference-application-name
        run: |
          REFERENCE_APPLICATION_NAME=${{ env.reference-application-name }}
          echo "::set-output name=value::$REFERENCE_APPLICATION_NAME"

      - name: Scalingo postgresql addon plan
        id: addon-plan-postgresql
        run: |
          POSTGRESQL_PLAN=$(echo ${{ env.addon-plan-postgresql }})
          echo "::set-output name=value::$POSTGRESQL_PLAN"          

      - name: Has a discord webhook for notification been defined
        id: is-discord-hooked
        run: |
          IS_HOOKED=${{ secrets.DISCORD_NOTIFY_HOOK_URL != '' }}
          echo "::set-output name=value::$IS_HOOKED"

      - name: Deployed domain url
        id: deployed-domain
        run: |
          DEPLOYED_DOMAIN=${{ steps.application-name.outputs.value }}.osc-fr1.scalingo.io
          echo "::set-output name=value::$DEPLOYED_DOMAIN"

      - name: Deployed friendly app name domain url
        id: deployed-app-name
        run: |
          DEPLOYED_APP_NAME=$(echo $BRANCH_SHORT_REF)
          echo "::set-output name=value::$DEPLOYED_APP_NAME"


  dependencies:
    runs-on: ubuntu-latest
    needs:
      - dynamic-variables

    outputs:
      pnpm_cache_path: ${{ steps.pnpm-cache.outputs.path }}
      pnpm_cache_key: ${{ steps.pnpm-cache.outputs.key }}

    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Expose pnpm cache configurationstore directory
        id: pnpm-cache
        run: |
          echo "::set-output name=path::$(pnpm store path)"
          echo "::set-output name=key::${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.path }}
          key: ${{ steps.pnpm-cache.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

  build:
    needs:
      - dependencies

    runs-on: ubuntu-latest

    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Retreives dependencies
        uses: actions/cache@v3
        with:
          key: ${{ needs.dependencies.outputs.pnpm_cache_key }}
          path: ${{ needs.dependencies.outputs.pnpm_cache_path }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        working-directory: front
        run: |
          VITE_GATEWAY=IN_MEMORY pnpm run build

      - name: Upload build bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-bundle
          path: front/dist


  validation:
    needs:
      - dependencies

    uses: ./.github/workflows/validation-front.yml
    with:
      cache-path: ${{ needs.dependencies.outputs.pnpm_cache_path }}
      cache-key: ${{ needs.dependencies.outputs.pnpm_cache_key }}

  deploy:
    needs:
      - dynamic-variables
      - build
      - validation
    uses: ./.github/workflows/_deploy-application.scalingo.reusable.yml
    with:
      application-full-name: ${{ needs.dynamic-variables.outputs.application-name }}
      scalingo-remote-domain-url: 'git@ssh.osc-fr1.scalingo.com'
      scalingo-ssh-host-domain: 'ssh.osc-fr1.scalingo.com'
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  notify-discord:
    if: ${{ needs.dynamic-variables.outputs.is-discord-hooked == 'true' }}
    needs:
      - dynamic-variables
      - deploy
    uses: ./.github/workflows/_notify-deployment.discord.reusable.yml
    with:
      deployer-name: "Scalingo Deployer"
      application-full-name: ${{ needs.dynamic-variables.outputs.deployed-app-name }}
      deployed-domain: ${{ needs.dynamic-variables.outputs.deployed-domain }}
    secrets:
      DISCORD_NOTIFY_HOOK_URL: ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
