name: Reusable Validation Workflow

on:
  workflow_call:
    inputs:
      cache-path:
        required: true
        type: string

      cache-key:
        required: true
        type: string

env:
  working-directory: ./front

jobs:
  includecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Check include script
        working-directory: front
        run: ./check_includes.sh

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Retrieve dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.cache-key }}
          path: ${{ inputs.cache-path }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: Check compilation
        working-directory: front
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Retrieve dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.cache-key }}
          path: ${{ inputs.cache-path }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: Execute tests
        working-directory: front
        run: pnpm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Retrieve dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.cache-key }}
          path: ${{ inputs.cache-path }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: eslint
        working-directory: front
        run: pnpm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the branch files
        uses: actions/checkout@v3

      - name: Retrieve dependencies
        uses: actions/cache@v3
        with:
          key: ${{ inputs.cache-key }}
          path: ${{ inputs.cache-path }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: prettier check
        working-directory: front
        run: pnpm run format:check
